apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: use-pv
  name: use-pvspec-shay
spec:
  volumes:
    - name: pv-analytics
      persistentVolumeClaim:
        claimName: pvc
  containers:
  - image: nginx
    name: use-pv
    volumeMounts:
        - mountPath: "/data/"
          name: pv-analytics
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}