apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
spec:
  containers:
  - name: alpha
    image: nginx
    env:
    - name: alpha
  - name: beta
    image: busybox
    env:
    - name: beta
    command: ["sleep","4800"]
    