apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
  template:
    metadata:
      labels:
    spec:
      containers:
      - name: app
        image: kodekloud/webapp-color
