apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: use-pv
  name: use-pvspec-shay
spec:
  volumes:
    - name: pv-1
      emptyDir: {} 
  containers:
  - image: nginx
    name: use-pv
    volumeMounts:
        - mountPath: "/data/"
          name: pv-1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}